Repository GnautSpace/Jura, pull requests merged in 2025-10, with the labels that each got.

#6 Added Error Handling in Backend part with Gemini 2.5
  backend/Docs/ERROR_HANDLING.md
  backend/LexiBotServer.cjs
  backend/nodemon.json
  backend/package-lock.json
  backend/package.json
  backend/server.cjs
Labels: hacktoberfest, hacktoberfest-2025

#11 feat: Added the dockerfile and docker compose to the project
  backend/Dockerfile
  docker-compose.yml
  frontend/Dockerfile
Labels: enhancement, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted

#21 Fixed Routing using useNavigate
  backend/package-lock.json
  frontend/src/App.jsx
  frontend/src/pages/Home.jsx
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-2025, hacktoberfest-accepted
